# Generated by Django 3.1.2 on 2020-11-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profe_is',
            field=models.IntegerField(default=0),
        ),
    ]
