# Generated by Django 3.1.2 on 2020-11-27 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcomuna', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(primary_key=True, serialize=False, verbose_name='IdRegion')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Sucursale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('idcomuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
            options={
                'db_table': 'sucursale',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('anio', models.CharField(max_length=50, verbose_name='año')),
                ('precio', models.IntegerField(default=10000, editable=False)),
                ('email', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='curso')),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('idSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursale')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='idregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region', verbose_name='IdRegion'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso', verbose_name='Curso')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
    ]
