# Generated by Django 3.1.2 on 2020-11-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursal',
            new_name='Sucursale',
        ),
    ]
