# Generated by Django 3.1.2 on 2020-11-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
