# Generated by Django 3.1.2 on 2020-11-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201110_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='comunaFk',
        ),
        migrations.AddField(
            model_name='sucursale',
            name='idcomuna',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
            preserve_default=False,
        ),
    ]
