# Generated by Django 3.1.2 on 2020-11-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201110_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.IntegerField(default=10000, editable=False),
        ),
    ]
